
(require 'color-theme)

;;;###autoload
(defun my-color-theme ()
  "Color theme by Yuji Minejima, created 2000-06-17."
  (interactive)
  (color-theme-install
   '(my-color-theme
     (;;(background-color . "darkslategrey")
      (foreground-color . "black")
      (background-color . "white")
      (background-mode . light)
      (border-color . "Black")
      (cursor-color . "Orange")
      ;;(foreground-color . "Wheat")
      ;;(mouse-color . "Grey")
      (mouse-color . "Black")
      )
     ((goto-address-mail-face . message-header-to-face)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . info-xref)
      (goto-address-url-mouse-face . highlight)
      (list-matching-lines-face . bold)
      (view-highlight-face . highlight))
     (default ((t (nil))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:italic t :bold t :foreground "beige"))))
     (calendar-today-face ((t (:underline t))))
     (cperl-array-face ((t (:foreground "Yellow"))))
     (cperl-hash-face ((t (:foreground "White"))))
     (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
     (custom-button-face ((t (:underline t :foreground "MediumSlateBlue"))))
     (custom-documentation-face ((t (:foreground "Grey"))))
     (custom-group-tag-face ((t (:foreground "MediumAquamarine"))))
     (custom-state-face ((t (:foreground "Coral"))))
     (custom-variable-tag-face ((t (:foreground "Aquamarine"))))
     (diary-face ((t (:bold t :foreground "IndianRed"))))
     (erc-action-face ((t (:bold t))))
     (erc-bold-face ((t (:bold t))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "LightSalmon"))))
     (erc-error-face ((t (:bold t :foreground "IndianRed"))))
     (erc-input-face ((t (:foreground "Beige"))))
     (erc-inverse-face ((t (:background "Wheat" :foreground "darkslategrey"))))
     (erc-notice-face ((t (:foreground "MediumAquamarine"))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:foreground "MediumAquamarine"))))
     (erc-underline-face ((t (:underline t))))
     (eshell-ls-archive-face ((t (:bold t :foreground "IndianRed"))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "DimGray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue"))))
     (eshell-ls-executable-face ((t (:bold t :foreground "Coral"))))
     (eshell-ls-missing-face ((t (:bold t :foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
     (eshell-ls-special-face ((t (:bold t :foreground "Gold"))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "White"))))
     (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
     (eshell-prompt-face ((t (:foreground "MediumAquamarine"))))
     (font-lock-builtin-face ((t (:bold t :foreground "MediumSeaGreen"))))
     (font-lock-comment-face ((t (:foreground "Blue"))))
     (font-lock-constant-face ((t (:bold t :foreground "MediumAquamarine"))))
     (font-lock-doc-string-face ((t (:foreground "dark sea green"))))
     (font-lock-function-name-face ((t (:bold t :foreground "Pink"))))
     (font-lock-keyword-face ((t (:foreground "Salmon"))))
     (font-lock-other-type-face ((t (:bold t))))
     (font-lock-reference-face ((t (:foreground "pale green"))))
     (font-lock-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-type-face ((t (:bold t :foreground "LimeGreen"))))
     (font-lock-variable-name-face ((t (:bold t :foreground "LightSteelBlue"))))
     (font-lock-warning-face ((t (:bold t :foreground "tomato"))))
     (gnus-cite-face-1 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-2 ((t (:foreground "chocolate"))))
     (gnus-cite-face-3 ((t (:foreground "tomato"))))
     (gnus-cite-face-4 ((t (:foreground "yellow green"))))
     (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
     (gnus-group-mail-1-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "light cyan"))))
     (gnus-group-mail-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "turquoise"))))
     (gnus-group-mail-3-empty-face ((t (:foreground "tomato"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "tomato"))))
     (gnus-group-mail-low-empty-face ((t (:foreground "dodger blue"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "dodger blue"))))
     (gnus-group-news-1-empty-face ((t (:foreground "green yellow"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "green yellow"))))
     (gnus-group-news-2-empty-face ((t (:foreground "dark orange"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "dark orange"))))
     (gnus-group-news-3-empty-face ((t (:foreground "tomato"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "tomato"))))
     (gnus-group-news-4-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-news-4-face ((t (:bold t :foreground "Aquamarine"))))
     (gnus-group-news-5-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-5-face ((t (:bold t :foreground "MediumAquamarine"))))
     (gnus-group-news-6-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-6-face ((t (:bold t :foreground "MediumAquamarine"))))
     (gnus-group-news-low-empty-face ((t (:foreground "yellow green"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "yellow green"))))
     (gnus-header-content-face ((t (:foreground "LightSkyBlue3"))))
     (gnus-header-from-face ((t (:bold t :foreground "light cyan"))))
     (gnus-header-name-face ((t (:bold t :foreground "DodgerBlue1"))))
     (gnus-header-newsgroups-face ((t (:bold t :foreground "LightSkyBlue3"))))
     (gnus-header-subject-face ((t (:bold t :foreground "light cyan"))))
     (gnus-signature-face ((t (:foreground "salmon"))))
     (gnus-splash-face ((t (:foreground "ForestGreen"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "CornflowerBlue"))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "LimeGreen"))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "OrangeRed"))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "Wheat"))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "chocolate"))))
     (gnus-summary-low-read-face ((t (:foreground "MediumSeaGreen"))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "IndianRed"))))
     (gnus-summary-low-unread-face ((t (:italic t :foreground "Wheat"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "CornflowerBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "LimeGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "orange red"))))
     (gnus-summary-normal-unread-face ((t (:foreground "Wheat"))))
     (gnus-summary-selected-face ((t (:underline t))))
     (highlight ((t (:background "PaleGreen" :foreground "DarkGreen"))))
     (highline-face ((t (:background "SeaGreen"))))
     (holiday-face ((t (:background "DimGray"))))
     (info-menu-5 ((t (:underline t))))
     (info-node ((t (:underline t :italic t :bold t :foreground "DodgerBlue1"))))
     (info-xref ((t (:bold t :foreground "DodgerBlue1"))))
     (isearch ((t (:background "red" :foreground "white"))))
     (italic ((t (:italic t))))
     (lookup-heading-1-face ((t (:bold t :foreground "LimeGreen"))))
     (lookup-heading-2-face ((t (:bold t :foreground "Red"))))
     (lookup-heading-3-face ((t (:bold t :foreground "Orange"))))
     (lookup-heading-4-face ((t (:bold t))))
     (lookup-heading-5-face ((t (nil))))
     (lookup-heading-low-face ((t (:foreground "Grey"))))
     (lookup-refered-face ((t (:underline t :foreground "Violet"))))
     (lookup-reference-face ((t (:underline t :foreground "LightSteelBlue"))))
     (message-cited-text-face ((t (:foreground "White"))))
     (message-header-cc-face ((t (:foreground "light cyan"))))
     (message-header-name-face ((t (:foreground "DodgerBlue1"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3"))))
     (message-header-other-face ((t (:foreground "LightSkyBlue3"))))
     (message-header-subject-face ((t (:bold t :foreground "light cyan"))))
     (message-header-to-face ((t (:bold t :foreground "light cyan"))))
     (message-header-xheader-face ((t (:foreground "DodgerBlue3"))))
     (message-separator-face ((t (:foreground "chocolate"))))
     (mew-highlight-mark-face-delete ((t (:foreground "LimeGreen"))))

     (modeline ((t (:background "DarkOliveGreen" :foreground "Wheat"))))
     (modeline-buffer-id ((t (:background "DarkOliveGreen" :foreground "beige"))))
     (modeline-mousable ((t (:background "DarkOliveGreen" :foreground "yellow green"))))
     (modeline-mousable-minor-mode ((t (:background "DarkOliveGreen" :foreground "Tan"))))
     (region ((t (:background "dark cyan" :foreground "cyan"))))
     ;(primary-selection ((t (:background "dark cyan" :foreground "cyan"))))
     (zmacs-region ((t (:background "dark cyan" :foreground "cyan"))))
     (list-mode-item-selected ((t (:background "dark cyan" :foreground "cyan"))))
     (secondary-selection ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (show-paren-match-face ((t (:background "Aquamarine" :foreground "SlateBlue"))))
     (show-paren-mismatch-face ((t (:background "Red" :foreground "White"))))
     (underline ((t (:underline t))))
     (widget-field-face ((t (:foreground "LightBlue"))))
     (widget-inactive-face ((t (:foreground "DimGray"))))
     (widget-single-line-field-face ((t (:foreground "LightBlue"))))
     (woman-bold-face ((t (:bold t))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face-mule-highlight-x-face-face ((t (:background "White" :foreground "Black")))))))

(my-color-theme)

(provide 'bm-color-theme)

;;; bm-color-theme.el ends here
